// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/openconnect/config.proto

package openconnect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Salted SHA-256, format "salt_hex$hash_hex".
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// Optional static IP address assigned to this user.
	Ip            string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proxy_openconnect_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_openconnect_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proxy_openconnect_config_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type OpenConnectInboundConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Users []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// Virtual address pool, e.g. "10.66.0.0/24".
	Subnet string   `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Dns    []string `protobuf:"bytes,3,rep,name=dns,proto3" json:"dns,omitempty"`
	// Base MTU advertised to the client. Default 1400.
	Mtu uint32 `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Dead-peer detection interval in seconds. Default 90.
	Dpd uint32 `protobuf:"varint,5,opt,name=dpd,proto3" json:"dpd,omitempty"`
	// Cookie validity after tunnel disconnect, in seconds. Default 300.
	CookieTimeout uint32 `protobuf:"varint,6,opt,name=cookie_timeout,json=cookieTimeout,proto3" json:"cookie_timeout,omitempty"`
	CertFile      string `protobuf:"bytes,7,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string `protobuf:"bytes,8,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	MaxClients    uint32 `protobuf:"varint,9,opt,name=max_clients,json=maxClients,proto3" json:"max_clients,omitempty"`
	// UDP (DTLS) listen port. 0 = same as the TCP listen port.
	DtlsPort      uint32 `protobuf:"varint,10,opt,name=dtls_port,json=dtlsPort,proto3" json:"dtls_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenConnectInboundConfig) Reset() {
	*x = OpenConnectInboundConfig{}
	mi := &file_proxy_openconnect_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenConnectInboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenConnectInboundConfig) ProtoMessage() {}

func (x *OpenConnectInboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_openconnect_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenConnectInboundConfig.ProtoReflect.Descriptor instead.
func (*OpenConnectInboundConfig) Descriptor() ([]byte, []int) {
	return file_proxy_openconnect_config_proto_rawDescGZIP(), []int{1}
}

func (x *OpenConnectInboundConfig) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *OpenConnectInboundConfig) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *OpenConnectInboundConfig) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *OpenConnectInboundConfig) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *OpenConnectInboundConfig) GetDpd() uint32 {
	if x != nil {
		return x.Dpd
	}
	return 0
}

func (x *OpenConnectInboundConfig) GetCookieTimeout() uint32 {
	if x != nil {
		return x.CookieTimeout
	}
	return 0
}

func (x *OpenConnectInboundConfig) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *OpenConnectInboundConfig) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *OpenConnectInboundConfig) GetMaxClients() uint32 {
	if x != nil {
		return x.MaxClients
	}
	return 0
}

func (x *OpenConnectInboundConfig) GetDtlsPort() uint32 {
	if x != nil {
		return x.DtlsPort
	}
	return 0
}

var File_proxy_openconnect_config_proto protoreflect.FileDescriptor

const file_proxy_openconnect_config_proto_rawDesc = "" +
	"\n" +
	"\x1eproxy/openconnect/config.proto\x12\x16xray.proxy.openconnect\"F\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"\xb9\x02\n" +
	"\x18OpenConnectInboundConfig\x122\n" +
	"\x05users\x18\x01 \x03(\v2\x1c.xray.proxy.openconnect.UserR\x05users\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\tR\x06subnet\x12\x10\n" +
	"\x03dns\x18\x03 \x03(\tR\x03dns\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\rR\x03mtu\x12\x10\n" +
	"\x03dpd\x18\x05 \x01(\rR\x03dpd\x12%\n" +
	"\x0ecookie_timeout\x18\x06 \x01(\rR\rcookieTimeout\x12\x1b\n" +
	"\tcert_file\x18\a \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\b \x01(\tR\akeyFile\x12\x1f\n" +
	"\vmax_clients\x18\t \x01(\rR\n" +
	"maxClients\x12\x1b\n" +
	"\tdtls_port\x18\n" +
	" \x01(\rR\bdtlsPortBd\n" +
	"\x1acom.xray.proxy.openconnectP\x01Z+github.com/xtls/xray-core/proxy/openconnect\xaa\x02\x16Xray.Proxy.OpenConnectb\x06proto3"

var (
	file_proxy_openconnect_config_proto_rawDescOnce sync.Once
	file_proxy_openconnect_config_proto_rawDescData []byte
)

func file_proxy_openconnect_config_proto_rawDescGZIP() []byte {
	file_proxy_openconnect_config_proto_rawDescOnce.Do(func() {
		file_proxy_openconnect_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_openconnect_config_proto_rawDesc), len(file_proxy_openconnect_config_proto_rawDesc)))
	})
	return file_proxy_openconnect_config_proto_rawDescData
}

var file_proxy_openconnect_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_openconnect_config_proto_goTypes = []any{
	(*User)(nil),                     // 0: xray.proxy.openconnect.User
	(*OpenConnectInboundConfig)(nil), // 1: xray.proxy.openconnect.OpenConnectInboundConfig
}
var file_proxy_openconnect_config_proto_depIdxs = []int32{
	0, // 0: xray.proxy.openconnect.OpenConnectInboundConfig.users:type_name -> xray.proxy.openconnect.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxy_openconnect_config_proto_init() }
func file_proxy_openconnect_config_proto_init() {
	if File_proxy_openconnect_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_openconnect_config_proto_rawDesc), len(file_proxy_openconnect_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_openconnect_config_proto_goTypes,
		DependencyIndexes: file_proxy_openconnect_config_proto_depIdxs,
		MessageInfos:      file_proxy_openconnect_config_proto_msgTypes,
	}.Build()
	File_proxy_openconnect_config_proto = out.File
	file_proxy_openconnect_config_proto_goTypes = nil
	file_proxy_openconnect_config_proto_depIdxs = nil
}
